/**
 * Request-independent message lookup for files generated by the import core (templates, error
 * reports, CLI output). Reads the locale JSON directly so it also works outside Next.js; messages
 * used here only contain simple `{placeholders}`.
 */
import arDataManagement from '../../../../locales/ar/dataManagement.json';
import arErrors from '../../../../locales/ar/errors.json';
import arStatuses from '../../../../locales/ar/statuses.json';
import enDataManagement from '../../../../locales/en/dataManagement.json';
import enErrors from '../../../../locales/en/errors.json';
import enStatuses from '../../../../locales/en/statuses.json';
import { fieldLabelKey, getField } from './schemas';
import type { ImportType, Issue } from './types';

export type MessageLocale = 'ar' | 'en';

const CATALOG: Record<MessageLocale, Record<string, unknown>> = {
  ar: { dataManagement: arDataManagement, errors: arErrors, statuses: arStatuses },
  en: { dataManagement: enDataManagement, errors: enErrors, statuses: enStatuses },
};

function lookup(locale: MessageLocale, key: string): string | null {
  let node: unknown = CATALOG[locale];
  for (const part of key.split('.')) {
    if (!node || typeof node !== 'object' || !(part in (node as Record<string, unknown>))) return null;
    node = (node as Record<string, unknown>)[part];
  }
  return typeof node === 'string' ? node : null;
}

/** `msg('ar', 'dataManagement.report.row')` with `{name}` substitution. Unknown keys return the key. */
export function msg(locale: MessageLocale, key: string, params: Record<string, string | number> = {}): string {
  const template = lookup(locale, key) ?? lookup('en', key) ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => (name in params ? String(params[name]) : `{${name}}`));
}

export function hasMsg(locale: MessageLocale, key: string): boolean {
  return lookup(locale, key) !== null;
}

/** Field label (`dataManagement.fields.*`) of an import field. */
export function fieldName(type: ImportType, key: string | undefined, locale: MessageLocale): string {
  if (!key) return '';
  const field = getField(type, key);
  return field ? msg(locale, `dataManagement.fields.${fieldLabelKey(field)}`) : key;
}

/** Parameters for `dataManagement.issues.<code>` (field label resolved, error reasons translated). */
export function issueParams(issue: Issue, type: ImportType, label: (key: string | undefined) => string, translate: (key: string) => string): Record<string, string | number> {
  const params: Record<string, string | number> = {
    row: '',
    rows: '',
    date: '',
    converted: '',
    name: '',
    number: '',
    nationalId: '',
    reason: '',
    ...issue.params,
    field: label(issue.field) || issue.column || '',
    column: issue.column ?? '',
    value: issue.value ?? '',
  };
  if (typeof params.reason === 'string' && params.reason) params.reason = translate(params.reason);
  void type;
  return params;
}

/** Full sentence for an issue in the given locale. */
export function issueText(issue: Issue, type: ImportType, locale: MessageLocale): string {
  const params = issueParams(issue, type, (k) => fieldName(type, k, locale), (k) => msg(locale, k));
  return msg(locale, `dataManagement.issues.${issue.code}`, params);
}
