// GENERATED by scripts/gen-db-types.mjs from the live database schema — do not edit by hand.
// Regenerate with `pnpm db:types` after every migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13"
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          changes: Json | null
          created_at: string
          employee_id: string | null
          entity_id: string | null
          entity_type: string | null
          id: number
          ip: string | null
          summary: string | null
          user_agent: string | null
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          changes?: Json | null
          created_at?: string
          employee_id?: string | null
          entity_id?: string | null
          entity_type?: string | null
          id?: never
          ip?: string | null
          summary?: string | null
          user_agent?: string | null
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          changes?: Json | null
          created_at?: string
          employee_id?: string | null
          entity_id?: string | null
          entity_type?: string | null
          id?: never
          ip?: string | null
          summary?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      certificate_template_versions: {
        Row: {
          change_notes: string | null
          changed_at: string
          changed_by: string | null
          id: string
          snapshot: Json
          template_id: string
          version: number
        }
        Insert: {
          change_notes?: string | null
          changed_at?: string
          changed_by?: string | null
          id?: string
          snapshot: Json
          template_id: string
          version: number
        }
        Update: {
          change_notes?: string | null
          changed_at?: string
          changed_by?: string | null
          id?: string
          snapshot?: Json
          template_id?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "certificate_template_versions_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificate_template_versions_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "certificate_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      certificate_templates: {
        Row: {
          certificate_type: string
          content_ar: string | null
          content_en: string | null
          created_at: string
          created_by: string | null
          current_version: number
          footer_html: string | null
          header_html: string | null
          id: string
          is_active: boolean
          is_default: boolean
          key: string
          language: string
          name_ar: string
          name_en: string
          published_at: string | null
          show_logo: boolean
          show_qr: boolean
          show_signature: boolean
          show_stamp: boolean
          updated_at: string
          updated_by: string | null
          variant: string
        }
        Insert: {
          certificate_type: string
          content_ar?: string | null
          content_en?: string | null
          created_at?: string
          created_by?: string | null
          current_version?: number
          footer_html?: string | null
          header_html?: string | null
          id?: string
          is_active?: boolean
          is_default?: boolean
          key: string
          language?: string
          name_ar: string
          name_en: string
          published_at?: string | null
          show_logo?: boolean
          show_qr?: boolean
          show_signature?: boolean
          show_stamp?: boolean
          updated_at?: string
          updated_by?: string | null
          variant?: string
        }
        Update: {
          certificate_type?: string
          content_ar?: string | null
          content_en?: string | null
          created_at?: string
          created_by?: string | null
          current_version?: number
          footer_html?: string | null
          header_html?: string | null
          id?: string
          is_active?: boolean
          is_default?: boolean
          key?: string
          language?: string
          name_ar?: string
          name_en?: string
          published_at?: string | null
          show_logo?: boolean
          show_qr?: boolean
          show_signature?: boolean
          show_stamp?: boolean
          updated_at?: string
          updated_by?: string | null
          variant?: string
        }
        Relationships: []
      }
      certificates: {
        Row: {
          addressed_to: string | null
          certificate_number: string
          certificate_type: string
          created_at: string
          created_by: string | null
          employee_id: string
          id: string
          issue_date: string
          issued_by: string | null
          language: string
          purpose: string | null
          request_id: string | null
          revoke_reason: string | null
          revoked_at: string | null
          status: string
          storage_path: string | null
          template_id: string | null
          template_version: number | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          addressed_to?: string | null
          certificate_number: string
          certificate_type: string
          created_at?: string
          created_by?: string | null
          employee_id: string
          id?: string
          issue_date?: string
          issued_by?: string | null
          language: string
          purpose?: string | null
          request_id?: string | null
          revoke_reason?: string | null
          revoked_at?: string | null
          status?: string
          storage_path?: string | null
          template_id?: string | null
          template_version?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          addressed_to?: string | null
          certificate_number?: string
          certificate_type?: string
          created_at?: string
          created_by?: string | null
          employee_id?: string
          id?: string
          issue_date?: string
          issued_by?: string | null
          language?: string
          purpose?: string | null
          request_id?: string | null
          revoke_reason?: string | null
          revoked_at?: string | null
          status?: string
          storage_path?: string | null
          template_id?: string | null
          template_version?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "certificates_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_issued_by_fkey"
            columns: ["issued_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "certificate_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      cost_centers: {
        Row: {
          code: string | null
          created_at: string
          created_by: string | null
          description_ar: string | null
          description_en: string | null
          id: string
          is_active: boolean
          name_ar: string | null
          name_en: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      departments: {
        Row: {
          code: string | null
          created_at: string
          created_by: string | null
          description_ar: string | null
          description_en: string | null
          head_employee_id: string | null
          id: string
          is_active: boolean
          name_ar: string | null
          name_en: string | null
          parent_id: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          head_employee_id?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          parent_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          head_employee_id?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          parent_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "departments_head_employee_id_fkey"
            columns: ["head_employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "departments_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
      document_sequences: {
        Row: {
          last_value: number
          prefix: string
          updated_at: string
          year: number
        }
        Insert: {
          last_value?: number
          prefix: string
          updated_at?: string
          year: number
        }
        Update: {
          last_value?: number
          prefix?: string
          updated_at?: string
          year?: number
        }
        Relationships: []
      }
      email_logs: {
        Row: {
          created_at: string
          created_by: string | null
          error: string | null
          id: string
          provider: string | null
          provider_message_id: string | null
          recipient: string
          related_entity_id: string | null
          related_entity_type: string | null
          sent_at: string | null
          status: string
          subject: string | null
          template_key: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: string
          provider?: string | null
          provider_message_id?: string | null
          recipient: string
          related_entity_id?: string | null
          related_entity_type?: string | null
          sent_at?: string | null
          status: string
          subject?: string | null
          template_key?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          error?: string | null
          id?: string
          provider?: string | null
          provider_message_id?: string | null
          recipient?: string
          related_entity_id?: string | null
          related_entity_type?: string | null
          sent_at?: string | null
          status?: string
          subject?: string | null
          template_key?: string | null
        }
        Relationships: []
      }
      email_templates: {
        Row: {
          body_ar: string
          body_en: string
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          key: string
          name_ar: string
          name_en: string
          placeholders: Json
          subject_ar: string
          subject_en: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          body_ar: string
          body_en: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          key: string
          name_ar: string
          name_en: string
          placeholders?: Json
          subject_ar: string
          subject_en: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          body_ar?: string
          body_en?: string
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          key?: string
          name_ar?: string
          name_en?: string
          placeholders?: Json
          subject_ar?: string
          subject_en?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      employee_bank_accounts: {
        Row: {
          account_holder: string | null
          bank_name: string | null
          created_at: string
          created_by: string | null
          employee_id: string
          iban: string | null
          id: string
          is_primary: boolean
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          account_holder?: string | null
          bank_name?: string | null
          created_at?: string
          created_by?: string | null
          employee_id: string
          iban?: string | null
          id?: string
          is_primary?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          account_holder?: string | null
          bank_name?: string | null
          created_at?: string
          created_by?: string | null
          employee_id?: string
          iban?: string | null
          id?: string
          is_primary?: boolean
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employee_bank_accounts_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_compensation: {
        Row: {
          basic_salary: number
          created_at: string
          created_by: string | null
          currency: string
          effective_date: string | null
          employee_id: string
          housing_allowance: number
          notes: string | null
          other_allowance: number
          total_salary: number | null
          transport_allowance: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          basic_salary?: number
          created_at?: string
          created_by?: string | null
          currency?: string
          effective_date?: string | null
          employee_id: string
          housing_allowance?: number
          notes?: string | null
          other_allowance?: number
          total_salary?: never
          transport_allowance?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          basic_salary?: number
          created_at?: string
          created_by?: string | null
          currency?: string
          effective_date?: string | null
          employee_id?: string
          housing_allowance?: number
          notes?: string | null
          other_allowance?: number
          total_salary?: never
          transport_allowance?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employee_compensation_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: true
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_dependents: {
        Row: {
          created_at: string
          created_by: string | null
          date_of_birth: string | null
          employee_id: string
          id: string
          insurance_member_number: string | null
          insurance_status: string | null
          iqama_expiry_date: string | null
          name_ar: string | null
          name_en: string | null
          national_id: string | null
          nationality: string | null
          notes: string | null
          passport_expiry_date: string | null
          passport_number: string | null
          relationship: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          employee_id: string
          id?: string
          insurance_member_number?: string | null
          insurance_status?: string | null
          iqama_expiry_date?: string | null
          name_ar?: string | null
          name_en?: string | null
          national_id?: string | null
          nationality?: string | null
          notes?: string | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          relationship: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          employee_id?: string
          id?: string
          insurance_member_number?: string | null
          insurance_status?: string | null
          iqama_expiry_date?: string | null
          name_ar?: string | null
          name_en?: string | null
          national_id?: string | null
          nationality?: string | null
          notes?: string | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          relationship?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employee_dependents_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_documents: {
        Row: {
          created_at: string
          created_by: string | null
          document_number: string | null
          document_type: string
          employee_id: string
          expiry_date: string | null
          file_name: string | null
          file_size: number | null
          id: string
          is_confidential: boolean
          issue_date: string | null
          mime_type: string | null
          notes: string | null
          status: string
          storage_path: string | null
          updated_at: string
          updated_by: string | null
          uploaded_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          document_number?: string | null
          document_type: string
          employee_id: string
          expiry_date?: string | null
          file_name?: string | null
          file_size?: number | null
          id?: string
          is_confidential?: boolean
          issue_date?: string | null
          mime_type?: string | null
          notes?: string | null
          status?: string
          storage_path?: string | null
          updated_at?: string
          updated_by?: string | null
          uploaded_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          document_number?: string | null
          document_type?: string
          employee_id?: string
          expiry_date?: string | null
          file_name?: string | null
          file_size?: number | null
          id?: string
          is_confidential?: boolean
          issue_date?: string | null
          mime_type?: string | null
          notes?: string | null
          status?: string
          storage_path?: string | null
          updated_at?: string
          updated_by?: string | null
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employee_documents_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employee_documents_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_insurance: {
        Row: {
          class: string | null
          created_at: string
          created_by: string | null
          dependent_id: string | null
          employee_id: string
          expiry_date: string | null
          id: string
          member_number: string | null
          policy_number: string | null
          provider: string | null
          start_date: string | null
          status: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          class?: string | null
          created_at?: string
          created_by?: string | null
          dependent_id?: string | null
          employee_id: string
          expiry_date?: string | null
          id?: string
          member_number?: string | null
          policy_number?: string | null
          provider?: string | null
          start_date?: string | null
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          class?: string | null
          created_at?: string
          created_by?: string | null
          dependent_id?: string | null
          employee_id?: string
          expiry_date?: string | null
          id?: string
          member_number?: string | null
          policy_number?: string | null
          provider?: string | null
          start_date?: string | null
          status?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employee_insurance_dependent_id_fkey"
            columns: ["dependent_id"]
            isOneToOne: false
            referencedRelation: "employee_dependents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employee_insurance_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      employees: {
        Row: {
          address: string | null
          alt_mobile: string | null
          archived_at: string | null
          archived_by: string | null
          avatar_path: string | null
          company_email: string | null
          contract_end_date: string | null
          contract_start_date: string | null
          cost_center_id: string | null
          created_at: string
          created_by: string | null
          date_of_birth: string | null
          department_id: string | null
          division: string | null
          emergency_contact_mobile: string | null
          emergency_contact_name: string | null
          emergency_contact_relationship: string | null
          employee_number: string | null
          employer_number: string | null
          employment_status: string
          employment_type: string | null
          extra_data: Json
          gender: string | null
          grade: string | null
          id: string
          id_type: string | null
          import_id: string | null
          iqama_expiry_date: string | null
          iqama_expiry_hijri: string | null
          iqama_issue_date: string | null
          iqama_profession: string | null
          is_outside_kingdom: boolean | null
          job_title_id: string | null
          joining_date: string | null
          location_id: string | null
          manager_id: string | null
          marital_status: string | null
          mobile: string | null
          name_ar: string | null
          name_en: string | null
          national_id: string | null
          nationality: string | null
          passport_expiry_date: string | null
          passport_number: string | null
          personal_email: string | null
          probation_end_date: string | null
          search_text: string | null
          section: string | null
          termination_date: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          address?: string | null
          alt_mobile?: string | null
          archived_at?: string | null
          archived_by?: string | null
          avatar_path?: string | null
          company_email?: string | null
          contract_end_date?: string | null
          contract_start_date?: string | null
          cost_center_id?: string | null
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          department_id?: string | null
          division?: string | null
          emergency_contact_mobile?: string | null
          emergency_contact_name?: string | null
          emergency_contact_relationship?: string | null
          employee_number?: string | null
          employer_number?: string | null
          employment_status?: string
          employment_type?: string | null
          extra_data?: Json
          gender?: string | null
          grade?: string | null
          id?: string
          id_type?: string | null
          import_id?: string | null
          iqama_expiry_date?: string | null
          iqama_expiry_hijri?: string | null
          iqama_issue_date?: string | null
          iqama_profession?: string | null
          is_outside_kingdom?: boolean | null
          job_title_id?: string | null
          joining_date?: string | null
          location_id?: string | null
          manager_id?: string | null
          marital_status?: string | null
          mobile?: string | null
          name_ar?: string | null
          name_en?: string | null
          national_id?: string | null
          nationality?: string | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          personal_email?: string | null
          probation_end_date?: string | null
          search_text?: never
          section?: string | null
          termination_date?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          address?: string | null
          alt_mobile?: string | null
          archived_at?: string | null
          archived_by?: string | null
          avatar_path?: string | null
          company_email?: string | null
          contract_end_date?: string | null
          contract_start_date?: string | null
          cost_center_id?: string | null
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          department_id?: string | null
          division?: string | null
          emergency_contact_mobile?: string | null
          emergency_contact_name?: string | null
          emergency_contact_relationship?: string | null
          employee_number?: string | null
          employer_number?: string | null
          employment_status?: string
          employment_type?: string | null
          extra_data?: Json
          gender?: string | null
          grade?: string | null
          id?: string
          id_type?: string | null
          import_id?: string | null
          iqama_expiry_date?: string | null
          iqama_expiry_hijri?: string | null
          iqama_issue_date?: string | null
          iqama_profession?: string | null
          is_outside_kingdom?: boolean | null
          job_title_id?: string | null
          joining_date?: string | null
          location_id?: string | null
          manager_id?: string | null
          marital_status?: string | null
          mobile?: string | null
          name_ar?: string | null
          name_en?: string | null
          national_id?: string | null
          nationality?: string | null
          passport_expiry_date?: string | null
          passport_number?: string | null
          personal_email?: string | null
          probation_end_date?: string | null
          search_text?: never
          section?: string | null
          termination_date?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "employees_cost_center_id_fkey"
            columns: ["cost_center_id"]
            isOneToOne: false
            referencedRelation: "cost_centers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_import_id_fkey"
            columns: ["import_id"]
            isOneToOne: false
            referencedRelation: "imports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_job_title_id_fkey"
            columns: ["job_title_id"]
            isOneToOne: false
            referencedRelation: "job_titles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_location_id_fkey"
            columns: ["location_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employees_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
        ]
      }
      hr_request_values: {
        Row: {
          created_at: string
          field_key: string
          id: string
          request_id: string
          updated_at: string
          value: Json
        }
        Insert: {
          created_at?: string
          field_key: string
          id?: string
          request_id: string
          updated_at?: string
          value: Json
        }
        Update: {
          created_at?: string
          field_key?: string
          id?: string
          request_id?: string
          updated_at?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "hr_request_values_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      hr_requests: {
        Row: {
          assigned_to: string | null
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          created_by: string | null
          current_approver_id: string | null
          current_step_id: string | null
          current_step_order: number | null
          current_step_type: string | null
          due_at: string | null
          employee_id: string
          id: string
          priority: string
          request_number: string | null
          request_type_id: string
          requester_id: string | null
          returned_from_step_order: number | null
          status: string
          submitted_at: string | null
          subtype: string | null
          title: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          assigned_to?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          current_approver_id?: string | null
          current_step_id?: string | null
          current_step_order?: number | null
          current_step_type?: string | null
          due_at?: string | null
          employee_id: string
          id?: string
          priority?: string
          request_number?: string | null
          request_type_id: string
          requester_id?: string | null
          returned_from_step_order?: number | null
          status?: string
          submitted_at?: string | null
          subtype?: string | null
          title?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          assigned_to?: string | null
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          current_approver_id?: string | null
          current_step_id?: string | null
          current_step_order?: number | null
          current_step_type?: string | null
          due_at?: string | null
          employee_id?: string
          id?: string
          priority?: string
          request_number?: string | null
          request_type_id?: string
          requester_id?: string | null
          returned_from_step_order?: number | null
          status?: string
          submitted_at?: string | null
          subtype?: string | null
          title?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "hr_requests_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_requests_current_approver_id_fkey"
            columns: ["current_approver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_requests_current_step_id_fkey"
            columns: ["current_step_id"]
            isOneToOne: false
            referencedRelation: "request_workflow_steps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_requests_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_requests_request_type_id_fkey"
            columns: ["request_type_id"]
            isOneToOne: false
            referencedRelation: "request_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "hr_requests_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      import_rows: {
        Row: {
          created_at: string
          entity_id: string | null
          errors: Json
          id: string
          import_id: string
          mapped: Json
          raw: Json
          row_number: number
          status: string
          warnings: Json
        }
        Insert: {
          created_at?: string
          entity_id?: string | null
          errors?: Json
          id?: string
          import_id: string
          mapped?: Json
          raw?: Json
          row_number: number
          status?: string
          warnings?: Json
        }
        Update: {
          created_at?: string
          entity_id?: string | null
          errors?: Json
          id?: string
          import_id?: string
          mapped?: Json
          raw?: Json
          row_number?: number
          status?: string
          warnings?: Json
        }
        Relationships: [
          {
            foreignKeyName: "import_rows_import_id_fkey"
            columns: ["import_id"]
            isOneToOne: false
            referencedRelation: "imports"
            referencedColumns: ["id"]
          },
        ]
      }
      imports: {
        Row: {
          completed_at: string | null
          created_at: string
          created_by: string | null
          error_rows: number
          file_name: string
          id: string
          import_type: string
          imported_rows: number
          mapping: Json
          options: Json
          status: string
          summary: Json
          total_rows: number
          updated_at: string
          updated_by: string | null
          valid_rows: number
          warning_rows: number
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          error_rows?: number
          file_name: string
          id?: string
          import_type: string
          imported_rows?: number
          mapping?: Json
          options?: Json
          status?: string
          summary?: Json
          total_rows?: number
          updated_at?: string
          updated_by?: string | null
          valid_rows?: number
          warning_rows?: number
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          error_rows?: number
          file_name?: string
          id?: string
          import_type?: string
          imported_rows?: number
          mapping?: Json
          options?: Json
          status?: string
          summary?: Json
          total_rows?: number
          updated_at?: string
          updated_by?: string | null
          valid_rows?: number
          warning_rows?: number
        }
        Relationships: []
      }
      job_titles: {
        Row: {
          code: string | null
          created_at: string
          created_by: string | null
          description_ar: string | null
          description_en: string | null
          id: string
          is_active: boolean
          name_ar: string | null
          name_en: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      leave_adjustments: {
        Row: {
          amount: number
          changed_at: string
          changed_by: string | null
          created_at: string
          id: string
          leave_balance_id: string
          new_remaining: number | null
          old_remaining: number | null
          reason: string
        }
        Insert: {
          amount: number
          changed_at?: string
          changed_by?: string | null
          created_at?: string
          id?: string
          leave_balance_id: string
          new_remaining?: number | null
          old_remaining?: number | null
          reason: string
        }
        Update: {
          amount?: number
          changed_at?: string
          changed_by?: string | null
          created_at?: string
          id?: string
          leave_balance_id?: string
          new_remaining?: number | null
          old_remaining?: number | null
          reason?: string
        }
        Relationships: [
          {
            foreignKeyName: "leave_adjustments_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_adjustments_leave_balance_id_fkey"
            columns: ["leave_balance_id"]
            isOneToOne: false
            referencedRelation: "leave_balances"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_balances: {
        Row: {
          adjustment: number
          created_at: string
          created_by: string | null
          employee_id: string
          entitlement: number
          id: string
          leave_type_id: string
          opening_balance: number
          pending: number
          remaining: number | null
          updated_at: string
          updated_by: string | null
          used: number
          year: number
        }
        Insert: {
          adjustment?: number
          created_at?: string
          created_by?: string | null
          employee_id: string
          entitlement?: number
          id?: string
          leave_type_id: string
          opening_balance?: number
          pending?: number
          remaining?: never
          updated_at?: string
          updated_by?: string | null
          used?: number
          year: number
        }
        Update: {
          adjustment?: number
          created_at?: string
          created_by?: string | null
          employee_id?: string
          entitlement?: number
          id?: string
          leave_type_id?: string
          opening_balance?: number
          pending?: number
          remaining?: never
          updated_at?: string
          updated_by?: string | null
          used?: number
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "leave_balances_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_balances_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_requests: {
        Row: {
          balance_effect: string
          created_at: string
          days: number
          employee_id: string
          end_date: string
          id: string
          leave_type_id: string
          request_id: string
          return_date: string | null
          start_date: string
          updated_at: string
          year: number
        }
        Insert: {
          balance_effect?: string
          created_at?: string
          days: number
          employee_id: string
          end_date: string
          id?: string
          leave_type_id: string
          request_id: string
          return_date?: string | null
          start_date: string
          updated_at?: string
          year: number
        }
        Update: {
          balance_effect?: string
          created_at?: string
          days?: number
          employee_id?: string
          end_date?: string
          id?: string
          leave_type_id?: string
          request_id?: string
          return_date?: string | null
          start_date?: string
          updated_at?: string
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "leave_requests_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: true
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_types: {
        Row: {
          code: string
          color: string
          created_at: string
          created_by: string | null
          day_count_basis: string
          deducts_balance: boolean
          default_entitlement: number
          description_ar: string | null
          description_en: string | null
          gender_restriction: string | null
          id: string
          is_active: boolean
          is_paid: boolean
          max_days_per_request: number | null
          name_ar: string
          name_en: string
          requires_attachment: boolean
          sort_order: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          code: string
          color?: string
          created_at?: string
          created_by?: string | null
          day_count_basis?: string
          deducts_balance?: boolean
          default_entitlement?: number
          description_ar?: string | null
          description_en?: string | null
          gender_restriction?: string | null
          id?: string
          is_active?: boolean
          is_paid?: boolean
          max_days_per_request?: number | null
          name_ar: string
          name_en: string
          requires_attachment?: boolean
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          code?: string
          color?: string
          created_at?: string
          created_by?: string | null
          day_count_basis?: string
          deducts_balance?: boolean
          default_entitlement?: number
          description_ar?: string | null
          description_en?: string | null
          gender_restriction?: string | null
          id?: string
          is_active?: boolean
          is_paid?: boolean
          max_days_per_request?: number | null
          name_ar?: string
          name_en?: string
          requires_attachment?: boolean
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      locations: {
        Row: {
          city: string | null
          code: string | null
          country: string | null
          created_at: string
          created_by: string | null
          description_ar: string | null
          description_en: string | null
          id: string
          is_active: boolean
          name_ar: string | null
          name_en: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          city?: string | null
          code?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          city?: string | null
          code?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      notification_settings: {
        Row: {
          created_at: string
          created_by: string | null
          email_enabled: boolean
          event_key: string
          id: string
          in_app_enabled: boolean
          recipients: Json
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          email_enabled?: boolean
          event_key: string
          id?: string
          in_app_enabled?: boolean
          recipients?: Json
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          email_enabled?: boolean
          event_key?: string
          id?: string
          in_app_enabled?: boolean
          recipients?: Json
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          created_at: string
          created_by: string | null
          emailed_at: string | null
          entity_id: string | null
          entity_type: string | null
          id: string
          link: string | null
          params: Json
          read_at: string | null
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          emailed_at?: string | null
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          link?: string | null
          params?: Json
          read_at?: string | null
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          emailed_at?: string | null
          entity_id?: string | null
          entity_type?: string | null
          id?: string
          link?: string | null
          params?: Json
          read_at?: string | null
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_settings: {
        Row: {
          allow_self_registration: boolean
          created_at: string
          created_by: string | null
          currency: string
          default_language: string
          email_from_name: string | null
          email_reply_to: string | null
          expiry_alert_days: number[]
          fiscal_year_start_month: number
          id: string
          login_image_path: string | null
          login_subtitle_ar: string | null
          login_subtitle_en: string | null
          login_title_ar: string | null
          login_title_en: string | null
          portal_name_ar: string
          portal_name_en: string
          primary_color: string
          secondary_color: string
          session_timeout_minutes: number
          setup_completed_at: string | null
          signatory_name_ar: string | null
          signatory_name_en: string | null
          signatory_title_ar: string | null
          signatory_title_en: string | null
          signature_path: string | null
          singleton: boolean
          stamp_path: string | null
          timezone: string
          updated_at: string
          updated_by: string | null
          weekend_days: number[]
          work_end: string
          work_start: string
          working_days: number[]
        }
        Insert: {
          allow_self_registration?: boolean
          created_at?: string
          created_by?: string | null
          currency?: string
          default_language?: string
          email_from_name?: string | null
          email_reply_to?: string | null
          expiry_alert_days?: number[]
          fiscal_year_start_month?: number
          id?: string
          login_image_path?: string | null
          login_subtitle_ar?: string | null
          login_subtitle_en?: string | null
          login_title_ar?: string | null
          login_title_en?: string | null
          portal_name_ar?: string
          portal_name_en?: string
          primary_color?: string
          secondary_color?: string
          session_timeout_minutes?: number
          setup_completed_at?: string | null
          signatory_name_ar?: string | null
          signatory_name_en?: string | null
          signatory_title_ar?: string | null
          signatory_title_en?: string | null
          signature_path?: string | null
          singleton?: boolean
          stamp_path?: string | null
          timezone?: string
          updated_at?: string
          updated_by?: string | null
          weekend_days?: number[]
          work_end?: string
          work_start?: string
          working_days?: number[]
        }
        Update: {
          allow_self_registration?: boolean
          created_at?: string
          created_by?: string | null
          currency?: string
          default_language?: string
          email_from_name?: string | null
          email_reply_to?: string | null
          expiry_alert_days?: number[]
          fiscal_year_start_month?: number
          id?: string
          login_image_path?: string | null
          login_subtitle_ar?: string | null
          login_subtitle_en?: string | null
          login_title_ar?: string | null
          login_title_en?: string | null
          portal_name_ar?: string
          portal_name_en?: string
          primary_color?: string
          secondary_color?: string
          session_timeout_minutes?: number
          setup_completed_at?: string | null
          signatory_name_ar?: string | null
          signatory_name_en?: string | null
          signatory_title_ar?: string | null
          signatory_title_en?: string | null
          signature_path?: string | null
          singleton?: boolean
          stamp_path?: string | null
          timezone?: string
          updated_at?: string
          updated_by?: string | null
          weekend_days?: number[]
          work_end?: string
          work_start?: string
          working_days?: number[]
        }
        Relationships: []
      }
      organizations: {
        Row: {
          address_ar: string | null
          address_en: string | null
          city: string | null
          commercial_registration: string | null
          country: string | null
          created_at: string
          created_by: string | null
          hr_email: string | null
          id: string
          legal_name_ar: string | null
          legal_name_en: string | null
          logo_path: string | null
          name_ar: string | null
          name_en: string | null
          phone: string | null
          singleton: boolean
          updated_at: string
          updated_by: string | null
          vat_number: string | null
          website: string | null
        }
        Insert: {
          address_ar?: string | null
          address_en?: string | null
          city?: string | null
          commercial_registration?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          hr_email?: string | null
          id?: string
          legal_name_ar?: string | null
          legal_name_en?: string | null
          logo_path?: string | null
          name_ar?: string | null
          name_en?: string | null
          phone?: string | null
          singleton?: boolean
          updated_at?: string
          updated_by?: string | null
          vat_number?: string | null
          website?: string | null
        }
        Update: {
          address_ar?: string | null
          address_en?: string | null
          city?: string | null
          commercial_registration?: string | null
          country?: string | null
          created_at?: string
          created_by?: string | null
          hr_email?: string | null
          id?: string
          legal_name_ar?: string | null
          legal_name_en?: string | null
          logo_path?: string | null
          name_ar?: string | null
          name_en?: string | null
          phone?: string | null
          singleton?: boolean
          updated_at?: string
          updated_by?: string | null
          vat_number?: string | null
          website?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          created_by: string | null
          email: string | null
          employee_id: string | null
          full_name: string | null
          id: string
          invited_at: string | null
          last_login_at: string | null
          matched_employee_id: string | null
          mobile: string | null
          preferred_language: string | null
          registration_employee_number: string | null
          registration_note: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          theme: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          employee_id?: string | null
          full_name?: string | null
          id: string
          invited_at?: string | null
          last_login_at?: string | null
          matched_employee_id?: string | null
          mobile?: string | null
          preferred_language?: string | null
          registration_employee_number?: string | null
          registration_note?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          theme?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          email?: string | null
          employee_id?: string | null
          full_name?: string | null
          id?: string
          invited_at?: string | null
          last_login_at?: string | null
          matched_employee_id?: string | null
          mobile?: string | null
          preferred_language?: string | null
          registration_employee_number?: string | null
          registration_note?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          theme?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: true
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_matched_employee_id_fkey"
            columns: ["matched_employee_id"]
            isOneToOne: false
            referencedRelation: "employees"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      public_holidays: {
        Row: {
          created_at: string
          created_by: string | null
          end_date: string
          id: string
          is_active: boolean
          name_ar: string | null
          name_en: string | null
          start_date: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          end_date: string
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          start_date: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          end_date?: string
          id?: string
          is_active?: boolean
          name_ar?: string | null
          name_en?: string | null
          start_date?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      request_approvals: {
        Row: {
          approver_id: string | null
          approver_name: string | null
          comment: string | null
          created_at: string
          decided_at: string | null
          decision: string
          id: string
          request_id: string
          step_id: string | null
          step_order: number
          step_type: string
        }
        Insert: {
          approver_id?: string | null
          approver_name?: string | null
          comment?: string | null
          created_at?: string
          decided_at?: string | null
          decision?: string
          id?: string
          request_id: string
          step_id?: string | null
          step_order: number
          step_type: string
        }
        Update: {
          approver_id?: string | null
          approver_name?: string | null
          comment?: string | null
          created_at?: string
          decided_at?: string | null
          decision?: string
          id?: string
          request_id?: string
          step_id?: string | null
          step_order?: number
          step_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "request_approvals_approver_id_fkey"
            columns: ["approver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_approvals_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_approvals_step_id_fkey"
            columns: ["step_id"]
            isOneToOne: false
            referencedRelation: "request_workflow_steps"
            referencedColumns: ["id"]
          },
        ]
      }
      request_attachments: {
        Row: {
          created_at: string
          field_key: string | null
          file_name: string
          file_size: number | null
          id: string
          mime_type: string | null
          request_id: string
          storage_path: string
          uploaded_by: string | null
        }
        Insert: {
          created_at?: string
          field_key?: string | null
          file_name: string
          file_size?: number | null
          id?: string
          mime_type?: string | null
          request_id: string
          storage_path: string
          uploaded_by?: string | null
        }
        Update: {
          created_at?: string
          field_key?: string | null
          file_name?: string
          file_size?: number | null
          id?: string
          mime_type?: string | null
          request_id?: string
          storage_path?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "request_attachments_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_attachments_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      request_comments: {
        Row: {
          author_id: string | null
          author_name: string | null
          body: string
          created_at: string
          id: string
          is_internal: boolean
          request_id: string
        }
        Insert: {
          author_id?: string | null
          author_name?: string | null
          body: string
          created_at?: string
          id?: string
          is_internal?: boolean
          request_id: string
        }
        Update: {
          author_id?: string | null
          author_name?: string | null
          body?: string
          created_at?: string
          id?: string
          is_internal?: boolean
          request_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "request_comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_comments_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      request_fields: {
        Row: {
          created_at: string
          created_by: string | null
          field_type: string
          help_ar: string | null
          help_en: string | null
          id: string
          is_active: boolean
          is_system: boolean
          key: string
          label_ar: string
          label_en: string
          options: Json
          placeholder_ar: string | null
          placeholder_en: string | null
          request_type_id: string
          required: boolean
          sort_order: number
          updated_at: string
          updated_by: string | null
          validation: Json
          visibility: Json | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          field_type: string
          help_ar?: string | null
          help_en?: string | null
          id?: string
          is_active?: boolean
          is_system?: boolean
          key: string
          label_ar: string
          label_en: string
          options?: Json
          placeholder_ar?: string | null
          placeholder_en?: string | null
          request_type_id: string
          required?: boolean
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
          validation?: Json
          visibility?: Json | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          field_type?: string
          help_ar?: string | null
          help_en?: string | null
          id?: string
          is_active?: boolean
          is_system?: boolean
          key?: string
          label_ar?: string
          label_en?: string
          options?: Json
          placeholder_ar?: string | null
          placeholder_en?: string | null
          request_type_id?: string
          required?: boolean
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
          validation?: Json
          visibility?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "request_fields_request_type_id_fkey"
            columns: ["request_type_id"]
            isOneToOne: false
            referencedRelation: "request_types"
            referencedColumns: ["id"]
          },
        ]
      }
      request_history: {
        Row: {
          action: string
          actor_id: string | null
          actor_name: string | null
          created_at: string
          from_status: string | null
          id: string
          metadata: Json
          note: string | null
          request_id: string
          to_status: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_name?: string | null
          created_at?: string
          from_status?: string | null
          id?: string
          metadata?: Json
          note?: string | null
          request_id: string
          to_status?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_name?: string | null
          created_at?: string
          from_status?: string | null
          id?: string
          metadata?: Json
          note?: string | null
          request_id?: string
          to_status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "request_history_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_history_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "hr_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      request_types: {
        Row: {
          allow_attachments: boolean
          category: string
          color: string | null
          created_at: string
          created_by: string | null
          description_ar: string | null
          description_en: string | null
          icon: string
          id: string
          is_active: boolean
          is_system: boolean
          key: string
          name_ar: string
          name_en: string
          requires_hr_approval: boolean
          requires_manager_approval: boolean
          sla_business_days: number | null
          sort_order: number
          updated_at: string
          updated_by: string | null
          workflow_id: string | null
        }
        Insert: {
          allow_attachments?: boolean
          category?: string
          color?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          icon?: string
          id?: string
          is_active?: boolean
          is_system?: boolean
          key: string
          name_ar: string
          name_en: string
          requires_hr_approval?: boolean
          requires_manager_approval?: boolean
          sla_business_days?: number | null
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
          workflow_id?: string | null
        }
        Update: {
          allow_attachments?: boolean
          category?: string
          color?: string | null
          created_at?: string
          created_by?: string | null
          description_ar?: string | null
          description_en?: string | null
          icon?: string
          id?: string
          is_active?: boolean
          is_system?: boolean
          key?: string
          name_ar?: string
          name_en?: string
          requires_hr_approval?: boolean
          requires_manager_approval?: boolean
          sla_business_days?: number | null
          sort_order?: number
          updated_at?: string
          updated_by?: string | null
          workflow_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "request_types_workflow_id_fkey"
            columns: ["workflow_id"]
            isOneToOne: false
            referencedRelation: "request_workflows"
            referencedColumns: ["id"]
          },
        ]
      }
      request_workflow_steps: {
        Row: {
          approver_role_key: string | null
          approver_user_id: string | null
          can_reassign: boolean
          can_return: boolean
          created_at: string
          created_by: string | null
          id: string
          name_ar: string
          name_en: string
          sla_business_days: number | null
          step_order: number
          step_type: string
          updated_at: string
          updated_by: string | null
          workflow_id: string
        }
        Insert: {
          approver_role_key?: string | null
          approver_user_id?: string | null
          can_reassign?: boolean
          can_return?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          name_ar: string
          name_en: string
          sla_business_days?: number | null
          step_order: number
          step_type: string
          updated_at?: string
          updated_by?: string | null
          workflow_id: string
        }
        Update: {
          approver_role_key?: string | null
          approver_user_id?: string | null
          can_reassign?: boolean
          can_return?: boolean
          created_at?: string
          created_by?: string | null
          id?: string
          name_ar?: string
          name_en?: string
          sla_business_days?: number | null
          step_order?: number
          step_type?: string
          updated_at?: string
          updated_by?: string | null
          workflow_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "request_workflow_steps_approver_role_key_fkey"
            columns: ["approver_role_key"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "request_workflow_steps_approver_user_id_fkey"
            columns: ["approver_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "request_workflow_steps_workflow_id_fkey"
            columns: ["workflow_id"]
            isOneToOne: false
            referencedRelation: "request_workflows"
            referencedColumns: ["id"]
          },
        ]
      }
      request_workflows: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          is_active: boolean
          name_ar: string
          name_en: string
          request_type_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          name_ar: string
          name_en: string
          request_type_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          is_active?: boolean
          name_ar?: string
          name_en?: string
          request_type_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "request_workflows_request_type_id_fkey"
            columns: ["request_type_id"]
            isOneToOne: false
            referencedRelation: "request_types"
            referencedColumns: ["id"]
          },
        ]
      }
      role_permissions: {
        Row: {
          action: string
          created_at: string
          created_by: string | null
          id: string
          module: string
          role_id: string
        }
        Insert: {
          action: string
          created_at?: string
          created_by?: string | null
          id?: string
          module: string
          role_id: string
        }
        Update: {
          action?: string
          created_at?: string
          created_by?: string | null
          id?: string
          module?: string
          role_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "role_permissions_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          created_at: string
          created_by: string | null
          data_scope: string
          description_ar: string | null
          description_en: string | null
          id: string
          is_system: boolean
          key: string
          name_ar: string
          name_en: string
          rank: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          data_scope?: string
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_system?: boolean
          key: string
          name_ar: string
          name_en: string
          rank?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string | null
          data_scope?: string
          description_ar?: string | null
          description_en?: string | null
          id?: string
          is_system?: boolean
          key?: string
          name_ar?: string
          name_en?: string
          rank?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      system_settings: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          key: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          role_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          role_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          role_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      act_on_request: {
        Args: { p_action: string; p_comment?: string; p_request_id: string; p_target_user?: string }
        Returns: Json
      }
      add_request_comment: {
        Args: { p_body: string; p_is_internal: boolean; p_request_id: string }
        Returns: string
      }
      adjust_leave_balance: {
        Args: { p_amount: number; p_employee_id: string; p_leave_type_id: string; p_reason: string; p_year: number }
        Returns: string
      }
      approve_registration: {
        Args: { p_employee_id?: string; p_profile_id: string; p_role_key?: string }
        Returns: undefined
      }
      audit_log_facets: {
        Args: { p_since?: string }
        Returns: {
            facet: string
            label: string
            total: number
            value: string
          }[]
      }
      claim_notification_emails: {
        Args: { p_notification_ids: string[] }
        Returns: {
            body: string
            email_from_name: string
            email_reply_to: string
            language: string
            link: string
            notification_id: string
            params: Json
            recipient_email: string
            recipient_name: string
            subject: string
            template_active: boolean
            template_key: string
            type: string
          }[]
      }
      count_leave_days: {
        Args: { p_end: string; p_leave_type_id: string; p_start: string }
        Returns: number
      }
      create_request_draft: {
        Args: { p_employee_id?: string; p_request_type_id: string; p_subtype?: string; p_values: Json }
        Returns: string
      }
      dashboard_employee_breakdown: {
        Args: never
        Returns: Json
      }
      dashboard_expiry_items: {
        Args: { p_days?: number; p_limit?: number }
        Returns: {
            days_left: number
            document_type: string
            employee_id: string
            employee_name_ar: string
            employee_name_en: string
            employee_number: string
            entity_id: string
            expiry_date: string
            kind: string
          }[]
      }
      dashboard_stats: {
        Args: never
        Returns: Json
      }
      generate_expiry_alerts: {
        Args: never
        Returns: number
      }
      get_employee_manager: {
        Args: { p_employee_id: string }
        Returns: Json
      }
      get_my_request_access: {
        Args: never
        Returns: Json
      }
      get_public_branding: {
        Args: never
        Returns: Json
      }
      get_request_capabilities: {
        Args: { p_request_id: string }
        Returns: Json
      }
      get_request_workflow: {
        Args: { p_request_id: string }
        Returns: {
            approver_id: string
            approver_name: string
            comment: string
            decided_at: string
            name_ar: string
            name_en: string
            state: string
            step_order: number
            step_type: string
          }[]
      }
      global_search: {
        Args: { p_limit?: number; p_locale?: string; p_query: string }
        Returns: {
            href: string
            id: string
            kind: string
            subtitle: string
            title: string
            type_key: string
          }[]
      }
      initialize_leave_balances: {
        Args: { p_employee_id?: string; p_year: number }
        Returns: number
      }
      list_request_assignees: {
        Args: { p_limit?: number; p_query?: string; p_request_id: string }
        Returns: {
            email: string
            employee_number: string
            full_name: string
            id: string
            job_title_ar: string
            job_title_en: string
            name_ar: string
            name_en: string
          }[]
      }
      list_request_handlers: {
        Args: never
        Returns: {
            email: string
            full_name: string
            id: string
            name_ar: string
            name_en: string
          }[]
      }
      log_audit_event: {
        Args: { p_action: string; p_changes?: Json; p_entity_id?: string; p_entity_type?: string; p_summary?: string }
        Returns: undefined
      }
      log_email: {
        Args: { p_error?: string; p_provider?: string; p_provider_message_id?: string; p_recipient: string; p_related_entity_id?: string; p_related_entity_type?: string; p_status: string; p_subject?: string; p_template_key?: string }
        Returns: string
      }
      master_data_usage: {
        Args: { p_entity: string }
        Returns: {
            all_employees: number
            children: number
            employees: number
            id: string
          }[]
      }
      next_document_number: {
        Args: { p_prefix: string }
        Returns: string
      }
      publish_certificate_template: {
        Args: { p_change_notes?: string; p_template_id: string }
        Returns: number
      }
      record_login: {
        Args: never
        Returns: undefined
      }
      reject_registration: {
        Args: { p_profile_id: string; p_reason: string }
        Returns: undefined
      }
      request_registration_info: {
        Args: { p_note: string; p_profile_id: string }
        Returns: undefined
      }
      reset_organization: {
        Args: { p_confirmation: string }
        Returns: undefined
      }
      restore_certificate_template_version: {
        Args: { p_template_id: string; p_version: number }
        Returns: undefined
      }
      set_leave_balance: {
        Args: { p_employee_id: string; p_entitlement?: number; p_leave_type_id: string; p_opening_balance: number; p_year: number }
        Returns: string
      }
      set_user_employee: {
        Args: { p_employee_id: string; p_user_id: string }
        Returns: undefined
      }
      set_user_roles: {
        Args: { p_role_keys: string[]; p_user_id: string }
        Returns: undefined
      }
      set_user_status: {
        Args: { p_note?: string; p_status: string; p_user_id: string }
        Returns: undefined
      }
      settings_overview: {
        Args: never
        Returns: Json
      }
      submit_request: {
        Args: { p_request_id: string }
        Returns: Json
      }
      update_request_draft: {
        Args: { p_request_id: string; p_subtype?: string; p_values: Json }
        Returns: undefined
      }
      verify_certificate: {
        Args: { p_number: string }
        Returns: {
            certificate_number: string
            certificate_type: string
            employee_name: string
            issue_date: string
            status: string
          }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
