-- =====================================================================================================
-- M7 Certificates — per-certificate verification code for the public /verify page.
--
-- Before: verify_certificate(p_number) was keyed by the SEQUENTIAL certificate number alone, so anyone
-- could enumerate CERT-YYYY-000001… with the anon key and harvest every certificate holder's name and
-- certificate type (e.g. who asked for a salary certificate, and when).
--
-- After:
--   * certificates.verification_code: 12 random characters (Crockford-style alphabet without 0/1/I/O,
--     60 bits), generated by the server action before the PDF is rendered and printed on the certificate
--     (QR target /verify/<number>?code=<code> + the code under the certificate number). Existing rows are
--     back-filled with a random code (their PDFs do not carry it, so they verify with the status only).
--   * issue_certificate(..., p_verification_code) stores it (validated; generated when omitted).
--   * verify_certificate(p_number, p_code default null) returns the same five columns, but
--     employee_name, certificate_type and issue_date are NULL unless p_code matches. A number alone only
--     confirms that the certificate exists and whether it is valid or revoked.
-- Idempotent.
-- =====================================================================================================

-- 60-bit random code from the CSPRNG behind gen_random_uuid() (12 fully random bytes of a v4 UUID,
-- each mapped to one of 32 symbols — 256 is a multiple of 32, so the mapping is unbiased).
create or replace function private.new_certificate_verification_code()
returns text
language plpgsql
volatile
set search_path = ''
as $$
declare
  v_alphabet constant text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  v_bytes    bytea := uuid_send(gen_random_uuid());
  v_code     text := '';
  i          int;
begin
  -- bytes 6 and 8 carry the UUID version / variant bits
  foreach i in array array[0, 1, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13] loop
    v_code := v_code || substr(v_alphabet, (get_byte(v_bytes, i) % 32) + 1, 1);
  end loop;
  return v_code;
end;
$$;

revoke execute on function private.new_certificate_verification_code() from public, anon, authenticated;

-- Normalizes user input: drops separators/spaces, upper-cases ("abcd-efgh-jkmn" → "ABCDEFGHJKMN").
create or replace function private.normalize_certificate_verification_code(p_code text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when p_code is null or length(p_code) > 40 then null
    else nullif(upper(regexp_replace(p_code, '[^0-9A-Za-z]', '', 'g')), '')
  end
$$;

revoke execute on function private.normalize_certificate_verification_code(text) from public, anon, authenticated;

-- A volatile default back-fills every existing row with its own random code.
alter table public.certificates
  add column if not exists verification_code text default private.new_certificate_verification_code();
update public.certificates set verification_code = private.new_certificate_verification_code() where verification_code is null;
alter table public.certificates alter column verification_code set default private.new_certificate_verification_code();
alter table public.certificates alter column verification_code set not null;
alter table public.certificates drop constraint if exists certificates_verification_code_check;
alter table public.certificates
  add constraint certificates_verification_code_check check (verification_code ~ '^[2-9A-HJ-NP-Z]{12}$');
comment on column public.certificates.verification_code is
  'Random 12-character code printed on the certificate (QR /verify/<number>?code=<code>). verify_certificate returns the holder''s name, type and issue date only when it matches.';

-- ---------------------------------------------------------------------------------------------------
-- issue_certificate: + p_verification_code (the code already printed on the rendered PDF)
-- ---------------------------------------------------------------------------------------------------
drop function if exists public.issue_certificate(text, uuid, uuid, uuid, int, text, text, text);

create or replace function public.issue_certificate(
  p_certificate_number text,
  p_request_id uuid,
  p_employee_id uuid,
  p_template_id uuid,
  p_template_version int,
  p_language text,
  p_addressed_to text default null,
  p_purpose text default null,
  p_verification_code text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tpl    public.certificate_templates;
  v_req    public.hr_requests;
  v_type   text;
  v_id     uuid;
  v_path   text;
  v_number text := upper(btrim(p_certificate_number));
  v_code   text := private.normalize_certificate_verification_code(p_verification_code);
begin
  if not private.has_org_permission('certificates', 'create') then
    raise exception 'hr:errors.forbidden' using errcode = '42501';
  end if;
  if v_number is null or v_number !~ '^CERT-[0-9]{4}-[0-9]{6,}$' then
    raise exception 'hr:errors.validation' using detail = 'certificate_number';
  end if;
  if p_language is null or p_language not in ('ar', 'en', 'bilingual') then
    raise exception 'hr:errors.validation' using detail = 'language';
  end if;
  if p_verification_code is not null and (v_code is null or v_code !~ '^[2-9A-HJ-NP-Z]{12}$') then
    raise exception 'hr:errors.validation' using detail = 'verification_code';
  end if;
  if not exists (select 1 from public.employees e where e.id = p_employee_id) then
    raise exception 'hr:errors.notFound' using errcode = 'P0002';
  end if;

  select * into v_tpl from public.certificate_templates where id = p_template_id;
  if not found then
    raise exception 'hr:errors.notFound' using errcode = 'P0002';
  end if;
  if not v_tpl.is_active or v_tpl.published_version is null or v_tpl.published_version <> p_template_version then
    raise exception 'hr:errors.templateNotPublished';
  end if;
  if not (v_tpl.language = 'bilingual' or v_tpl.language = p_language) then
    raise exception 'hr:errors.templateLanguageMismatch' using detail = 'language';
  end if;

  if p_request_id is not null then
    select * into v_req from public.hr_requests where id = p_request_id for update;
    if not found then
      raise exception 'hr:errors.notFound' using errcode = 'P0002';
    end if;
    select rt.key into v_type from public.request_types rt where rt.id = v_req.request_type_id;
    if v_type is distinct from 'certificate' or v_req.employee_id is distinct from p_employee_id then
      raise exception 'hr:errors.validation' using detail = 'request_id';
    end if;
    if v_req.status not in ('pending_hr_review', 'approved', 'in_progress', 'completed') then
      raise exception 'hr:errors.invalidTransition';
    end if;
  end if;

  v_path := 'certificates/' || p_employee_id::text || '/' || v_number || '.pdf';
  -- the PDF must already be stored (the server action renders and uploads it first)
  if not exists (select 1 from storage.objects o where o.bucket_id = 'certificate-files' and o.name = v_path) then
    raise exception 'hr:errors.validation' using detail = 'file';
  end if;

  insert into public.certificates (certificate_number, employee_id, request_id, template_id, template_version, certificate_type,
                                   language, addressed_to, purpose, issue_date, status, storage_path, issued_by, verification_code)
  values (v_number, p_employee_id, p_request_id, p_template_id, p_template_version, v_tpl.certificate_type,
          p_language, left(private.nullif_blank(p_addressed_to), 200), left(private.nullif_blank(p_purpose), 300),
          private.org_today(), 'valid', v_path, auth.uid(), coalesce(v_code, private.new_certificate_verification_code()))
  returning id into v_id;

  if p_request_id is not null then
    insert into public.request_history (request_id, action, from_status, to_status, actor_id, actor_name, note, metadata)
    values (p_request_id, 'certificate_issued', v_req.status, v_req.status, auth.uid(), private.profile_display_name(auth.uid()),
            v_number, jsonb_build_object('certificate_id', v_id, 'certificate_number', v_number,
                                         'certificate_type', v_tpl.certificate_type, 'language', p_language));
  end if;

  return v_id;
end;
$$;

revoke execute on function public.issue_certificate(text, uuid, uuid, uuid, int, text, text, text, text) from public, anon;
grant execute on function public.issue_certificate(text, uuid, uuid, uuid, int, text, text, text, text) to authenticated, service_role;

-- ---------------------------------------------------------------------------------------------------
-- verify_certificate: holder name, type and issue date only with the matching code
-- ---------------------------------------------------------------------------------------------------
drop function if exists public.verify_certificate(text);

create or replace function public.verify_certificate(p_number text, p_code text default null)
returns table (certificate_number text, employee_name text, certificate_type text, issue_date date, status text)
language sql
stable
security definer
set search_path = ''
as $$
  select c.certificate_number,
         case when k.ok then
           case c.language
             when 'en' then coalesce(nullif(e.name_en, ''), e.name_ar)
             when 'ar' then coalesce(nullif(e.name_ar, ''), e.name_en)
             else concat_ws(' / ', nullif(e.name_ar, ''), nullif(e.name_en, ''))
           end
         end,
         case when k.ok then c.certificate_type end,
         case when k.ok then c.issue_date end,
         c.status
  from public.certificates c
  join public.employees e on e.id = c.employee_id
  cross join lateral (
    select coalesce(private.normalize_certificate_verification_code(p_code) = c.verification_code, false) as ok
  ) k
  where p_number is not null
    and length(p_number) <= 40
    and upper(btrim(p_number)) = c.certificate_number
  limit 1
$$;

revoke execute on function public.verify_certificate(text, text) from public;
grant execute on function public.verify_certificate(text, text) to anon, authenticated, service_role;

comment on function public.verify_certificate(text, text) is
  'Public (anon) certificate check. Always: certificate_number, status. employee_name, certificate_type, issue_date: only when p_code matches certificates.verification_code.';
